// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    $(document).foundation();
    return skrollr.init({
      smoothScrolling: false,
      mobileDeceleration: 0.004
    });
  });

}).call(this);

//# sourceMappingURL=website.map
